spring:
  cloud:
    gateway:
       routes:
          - id: r1
            uri: http://localhost:8081/
            predicates:
              - Path= Path= /customer/**
          - id: r2
            uri: http://localhost:8082/
            predicates:
              - Path= /inventory/**
    discovery:
      enabled: false
server:
  port: 8888

